import React, { createContext, useContext, useState, useEffect } from 'react';
import api from '../api/client';

const CaseContext = createContext();

export const CaseProvider = ({ children }) => {
  const [activeConsultationId, setActiveConsultationId] = useState(() => {
    const mode = localStorage.getItem('aarogya_case_mode');
    const stored = localStorage.getItem('aarogya_active_con_id');
    // Persist the active case across refreshes. Demo IDs are intentionally
    // generated by the backend, so never assume a fixed AS-CON-2026-0001.
    return stored || null;
  });
  const [activePatientId, setActivePatientId] = useState(() => {
    const mode = localStorage.getItem('aarogya_case_mode');
    const stored = localStorage.getItem('aarogya_active_pat_id');
    return stored || null;
  });
  const [activeConsultation, setActiveConsultation] = useState(null);
  const [activePatient, setActivePatient] = useState(null);
  const [loadingCase, setLoadingCase] = useState(false);

  const fetchActiveCase = async (conId = activeConsultationId) => {
    if (!conId) return;
    setLoadingCase(true);
    try {
      const res = await api.get(`/consultations/${conId}`);
      if (res.data.success && res.data.data) {
        setActiveConsultation(res.data.data);
        if (res.data.data.patient) {
          setActivePatient(res.data.data.patient);
          const patientId = res.data.data.patient.patientId || res.data.data.patientId;
          setActivePatientId(patientId);
          localStorage.setItem('aarogya_active_pat_id', patientId);
        }
      }
    } catch (err) {
      console.warn('Could not fetch active consultation:', err.message);
      // If a generated demo case was cleared, remove the stale pointer rather
      // than trapping the UI on a permanent 404. The next Demo Login can seed
      // a fresh case and update the context.
      if (err.response?.status === 404) {
        localStorage.removeItem('aarogya_active_con_id');
        localStorage.removeItem('aarogya_active_pat_id');
        localStorage.removeItem('aarogya_case_mode');
        setActiveConsultationId(null);
        setActivePatientId(null);
        setActiveConsultation(null);
        setActivePatient(null);
      }
    } finally {
      setLoadingCase(false);
    }
  };

  useEffect(() => {
    if (activeConsultationId) {
      fetchActiveCase(activeConsultationId);
    }
  }, [activeConsultationId]);

  const setActiveCase = (consultationId, patientId) => {
    setActiveConsultationId(consultationId);
    if (patientId) setActivePatientId(patientId);
    localStorage.setItem('aarogya_active_con_id', consultationId);
    if (patientId) localStorage.setItem('aarogya_active_pat_id', patientId);
    localStorage.setItem('aarogya_case_mode', String(consultationId).startsWith('AS-CON-2026-') ? 'demo' : 'custom');
  };

  const loadDemoPatient = async () => {
    setLoadingCase(true);
    try {
      const res = await api.post('/demo/seed');
      if (res.data.success) {
        const { consultationId, patientId } = res.data.data;
        setActiveCase(consultationId, patientId);
        return res.data;
      }
    } catch (err) {
      console.error('Failed to seed demo patient:', err);
      throw err;
    } finally {
      setLoadingCase(false);
    }
  };

  const refreshCase = () => {
    if (activeConsultationId) {
      fetchActiveCase(activeConsultationId);
    }
  };

  return (
    <CaseContext.Provider
      value={{
        activeConsultationId,
        activePatientId,
        activeConsultation,
        activePatient,
        loadingCase,
        setActiveCase,
        loadDemoPatient,
        refreshCase
      }}
    >
      {children}
    </CaseContext.Provider>
  );
};

export const useCase = () => useContext(CaseContext);
